### ISSUE TITLE
Disable https on Docker

### ISSUE THREAD

**Issue by Blackraz0r** [mroote/factorio-server-manager#184]
Can i disable HTTPS and only use HTTP on the docker version somehow?

i want to access it trough a reverse proxy anyway so HTTPS internally will just over-complicate things.

thank you for help =)

**Comment by knoxfighter** [comment]
inside the docker image, factorio is using port 80 for http and https is disabled by default.
Therefore you can use the reverseproxy simply. 
My reverse proxy setup with traevik:
```
version: '3.7'
services:
    factorio-manager-1-0:
        container_name: factorio-manager-1-0
        build: .
        restart: always
        volumes:
            - "./saves:/opt/factorio/saves"
            - "./mods:/opt/factorio/mods"
            - "./config:/opt/factorio/config"
        expose:
            - "80"
        ports:
            - "<ip>:34197:34197/udp"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.factorio.rule=Host(`<domain>`)"
            - "traefik.http.routers.factorio.entrypoints=websecure"
            - "traefik.http.routers.factorio.tls.certresolver=le"
            - "traefik.docker.network=web_traefik"

networks:
  default:
    external:
      name: web_traefik
```
